### ISSUE TITLE
Upgrade to Material UI v5

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-react-components#163]
## Goals
Upgrade to Material UI v5

## Requirements
- Upgrade to the latest version of Material UI.

## Links
- [Migration guide](https://mui.com/guides/migration-v4/)

**Comment by paulrberg** [comment]
this would be great! Just hit this error while developing my app.

> Module not found: Can't resolve '@material-ui/core/Accordion' in '/Users/paulrberg/workspace/sablier/v1-gnosis-app/node_modules/@gnosis.pm/safe-react-components/dist'
